; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_qtpy_esp32s2]
platform = espressif32
board = adafruit_qtpy_esp32s2
framework = arduino
targets = upload
build_unflags = -Os
build_flags = -O3  -D TARGET_QTPYS2
upload_port = COM3
monitor_speed = 115200
lib_deps = 
	arkhipenko/TaskScheduler@^3.7.0
	playingwithfusion/PWFusion_TCA9548A@^1.0.1
	bblanchon/ArduinoJson@^6.19.4
	adafruit/Adafruit BusIO@^1.14.1
	adafruit/Adafruit Unified Sensor@^1.1.7    

[env:azDelivery_Wroom_32]
platform = espressif32
board = nodemcu-32s
framework = arduino
targets = upload
build_unflags = -Os
build_flags = -O3 -D TARGET_WROOM
upload_port = COM12
monitor_speed = 115200
lib_deps = 
	arkhipenko/TaskScheduler@^3.7.0
	playingwithfusion/PWFusion_TCA9548A@^1.0.1
